# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/btech/cs1190372/col215/vivado/a5/a5.cache/wt [current_project]
set_property parent.project_path /home/btech/cs1190372/col215/vivado/a5/a5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/btech/cs1190372/col215/vivado/a5/a5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/btech/cs1190372/col215/vivado/a5/a5.srcs/sources_1/new/bch_to_display.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/btech/cs1190372/col215/vivado/a5/a5.srcs/constrs_1/new/master.xdc
set_property used_in_implementation false [get_files /home/btech/cs1190372/col215/vivado/a5/a5.srcs/constrs_1/new/master.xdc]


synth_design -top bch_to_display -part xc7a35tcpg236-1


write_checkpoint -force -noxdef bch_to_display.dcp

catch { report_utilization -file bch_to_display_utilization_synth.rpt -pb bch_to_display_utilization_synth.pb }
